import{R as r,q as u,o as M,a1 as b,j as t,a2 as y,a3 as j}from"./DEYDuN7xp-m3cL830AkD.js";import{u as A}from"./DMCex30FeWvvThtDj-pY.js";import{u as C}from"./zdDLXtJuoQIQMZlDPq5d.js";import{P as E}from"./B8a7_oPVuhqv4mSPchaN.js";import{H as S}from"./D5IfCODi1RtN0YG4PG7p.js";import{M as w}from"./D7CtA6kbyc14jOEqqnsG.js";const G=r.createContext(0),R=82,L=u.div`
	flex: 1 1 auto;
	overflow-y: auto;
	display: flex;
	flex-direction: column-reverse;
`,P=u.div`
	margin: 16px 16px 0 16px;
`;function D({guild:n,channel:e}){const l=C(),a=A("MessageList.tsx"),[d,c]=r.useState(!0),[p,m]=r.useState(!1),o=e.messages.groups,f=r.useRef(null),{width:h}=b({ref:f});r.useEffect(()=>{const i=E.getPermission(l.account.id,n,e).has("READ_MESSAGE_HISTORY");if(m(i),!i){a.debug("User cannot view this channel. Aborting initial message fetch.");return}return n&&e&&e.messages.count===0&&e.getMessages(l,!0).then(g=>{g<50&&c(!1)}),()=>{a.debug("MessageList unmounted"),c(!0),m(!1)}},[n,e]);const x=r.useCallback(()=>{if(!e.messages.count){a.warn("channel has no messages, aborting!");return}const s=o[o.length-1];if(!s){a.warn("No last group found, aborting fetchMore");return}if("status"in s.messages[0])return;const i=s.messages[0].id;a.debug(`Fetching 50 messages before ${i} for channel ${e.id}`),e.getMessages(l,!1,50,i).then(g=>{g<50&&c(!1)})},[e,o]),v=r.useCallback(s=>t.jsx(w,{group:s},`messageGroup-${s.messages[s.messages.length-1].id}`),[o]);return t.jsx(G.Provider,{value:(h??0)-R,children:t.jsx(L,{id:"scrollable-div",ref:f,children:p?t.jsx(y,{dataLength:o.length,next:x,style:{display:"flex",flexDirection:"column-reverse",marginBottom:30,overflow:"hidden"},hasMore:d,inverse:!0,loader:t.jsx(j,{style:{display:"flex",justifyContent:"center",alignContent:"center",margin:30},color:"var(--primary)"}),scrollThreshold:.5,scrollableTarget:"scrollable-div",endMessage:t.jsxs(P,{children:[t.jsxs("h1",{style:{fontWeight:700,margin:"8px 0"},children:["Welcome to #",e.name,"!"]}),t.jsxs("p",{style:{color:"var(--text-secondary)"},children:["This is the start of the #",e.name," channel."]}),t.jsx(S,{})]}),children:o.map(s=>v(s))}):t.jsx("div",{style:{marginBottom:30,paddingLeft:20,color:"var(--text-secondary)"},children:"You do not have permission to read the history of this channel."})})})}const k=M(D);export{k as M,G as a};
//# sourceMappingURL=Bh2fBHGoM6jnaDynWtED.js.map
